Bump versions; Add Dockerized aws

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -1,56 +1,62 @@
 #!/usr/bin/env bash
 
-tf_output=$(./terraform output -json)
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+export PATH="${DIR}:${PATH}"
 
-export aws_region
-aws_region=$(echo "${tf_output}" | jq -r '.aws_region.value')
-export backup_profile
-backup_profile=$(echo "${tf_output}" | jq -r '.backup_profile.value')
-export state_machine_arn
+if [[ -z "$(command -v jq)" ]] ; then
+  echo "jq not found"
+  exit 1
+fi
+
+tf_output=$(terraform output -json)
+
+export AWS_REGION
+AWS_REGION=$(echo "${tf_output}" | jq -r '.aws_region.value')
+export AWS_PROFILE
+AWS_PROFILE=$(echo "${tf_output}" | jq -r '.backup_profile.value')
+
 state_machine_arn=$(echo "${tf_output}" | jq -r '.state_machine_arn.value')
 
+
 start_execution() {
+  local state_machine_arn="${1}"
   aws stepfunctions start-execution \
     --state-machine-arn "${state_machine_arn}" \
-    --profile "${backup_profile}" \
-    --region "${aws_region}" \
     | jq -r '.executionArn'
 }
 
 get_state_entered() {
+  local execution_arn="${1}"
   aws stepfunctions get-execution-history \
     --execution-arn "${execution_arn}" \
     --reverse-order \
     --max-items 1 \
-    --profile "${backup_profile}" \
-    --region "${aws_region}" \
     | jq -r '.events[] | .stateEnteredEventDetails? | .name'
 }
 
 get_stop_date() {
+  local execution_arn="${1}"
   aws stepfunctions describe-execution \
     --execution-arn "${execution_arn}" \
-    --profile "${backup_profile}" \
-    --region "${aws_region}" \
     | jq -r '.stopDate'
 }
 
 get_execution_failed_cause() {
+  local execution_arn="${1}"
   aws stepfunctions get-execution-history \
     --execution-arn "${execution_arn}" \
     --reverse-order \
     --max-items 1 \
-    --profile "${backup_profile}" \
-    --region "${aws_region}" \
     | jq -r '.events[] | .executionFailedEventDetails? | .cause'
 }
 
-execution_arn=$(start_execution)
-echo "Starting ${execution_arn}..."
+
+execution_arn=$(start_execution "${state_machine_arn}")
+echo "Starting ${execution_arn} ..."
 
 while true; do
-  state_entered=$(get_state_entered)
-  stop_date=$(get_stop_date)
+  state_entered=$(get_state_entered "${execution_arn}")
+  stop_date=$(get_stop_date "${execution_arn}")
 
   if [[ -n "${state_entered}" ]] && [[ "${state_entered}" != "null" ]] ; then
     echo "${state_entered}"
@@ -62,7 +68,7 @@ while true; do
   sleep 60
 done
 
-failed_cause=$(get_execution_failed_cause)
+failed_cause=$(get_execution_failed_cause "${execution_arn}")
 if [[ -n "${failed_cause}" ]] && [[ "${failed_cause}" != "null" ]] ; then
   echo "${failed_cause}"
 fi
